# yaml-language-server: $schema=https://static.codemagic.io/codemagic-schema.json
workflows:
  ci:
    name: CI
    instance_type: mac_mini_m1
    max_build_duration: 15
    environment:
      flutter: 3.10.0
      xcode: latest
    cache:
      cache_paths:
        - ~/.pub-cache
    triggering:
      events:
        - push
      cancel_previous_builds: false
    scripts:
      - name: Lint
        script: flutter analyze
      - name: Test
        script: |
          mkdir -p test-results
          flutter test --machine > test-results/tests.json
        test_report: test-results/tests.json
